# 작성법 
#[액션] [프로토콜] [출발지 IP] [포트] [방향] [목적지 IP] [포트] (msg:"공격 탐지명"; content:"공격문구"; flags:S; sid:1000001; rev:1;)
# alert ip 172.31.0.0/16 any -> any any (msg:"이렇게 작성"; content:"이거있으면"; flags:S(SYN 패킷); sid:1씩 증가하게 할예정; rev:1;)
# 조건 : threshold , 대소문자 구분 X : nocase;


