- hosts: server
  become: yes

  tasks:

    - name: install curl
      apt:
        name: curl
        state: present
        update_cache: yes


    - name: install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash


    - name: wait k3s
      shell: |
        sleep 10


    - name: check node
      shell: |
        sudo k3s kubectl get nodes
      register: result


    - debug:
        var: result.stdout
